import { AskBar } from "@/components/ask-bar";
import { ErrorNotice } from "@/components/error-notice";
import { ProjectList } from "@/components/project-list";
import { UploadForm } from "@/components/upload-form";
import { hasDatabaseConfig } from "@/db/client";
import { embeddingsEnv, isConfigured, llmEnv } from "@/lib/env";
import {
  loadAssessmentsForPage,
  loadIndexedSourcesForPage,
  loadLatestRunsForPage,
  loadProjectsForPage,
} from "@/lib/page-data";
import { getOwnerId } from "@/lib/session";

import type { IndexedSourceListing } from "@/lib/report/types";

/**
 * The one continuous project page. Layers 1–4 of the design land on this page in
 * later milestones; what exists here is the entry point — upload, session-scoped
 * project list — plus an environment panel so a half-configured deployment
 * explains itself instead of failing opaquely.
 */

function CapabilityRow({ label, detail, ready }: { label: string; detail: string; ready: boolean }) {
  return (
    <li className="flex items-baseline justify-between gap-4 border-b border-[var(--border-subtle)] py-1.5 last:border-b-0">
      <span className="flex items-center gap-2">
        <span
          aria-hidden
          className={`inline-block size-1.5 rounded-full ${ready ? "bg-[var(--risk-low)]" : "bg-[var(--risk-unknown)]"}`}
        />
        <span className="text-[13px]">{label}</span>
      </span>
      <span className="meta text-right">{detail}</span>
    </li>
  );
}

/**
 * The environment, as a footer rather than a feature: it is a deployment
 * diagnosis, and a reader who has a working scorecard should not have to scroll
 * past it. One line per capability, with the reason a missing one matters kept in
 * the note below instead of next to the row.
 */
function EnvironmentPanel() {
  const embeddingsReady = isConfigured(embeddingsEnv);
  const llmReady = isConfigured(llmEnv);

  return (
    <section className="panel-quiet px-5 py-4" aria-labelledby="environment-heading">
      <div className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-1">
        <h2 id="environment-heading" className="eyebrow">
          Environment
        </h2>
        <p className="meta measure">
          Scores are computed from structured findings by a documented rubric, not generated by a model.
          The scorecard stays available even when the LLM paths are not.
        </p>
      </div>
      <ul className="mt-2">
        <CapabilityRow label="Database" detail="configured" ready />
        <CapabilityRow
          label="LLM"
          detail={llmReady ? `configured · ${llmEnv().LLM_MODEL}` : "DEEPSEEK_API_KEY not set"}
          ready={llmReady}
        />
        <CapabilityRow
          label="Embeddings"
          detail={embeddingsReady ? `${embeddingsEnv().EMBEDDING_MODEL} via Ollama` : "Ollama not configured"}
          ready={embeddingsReady}
        />
      </ul>
    </section>
  );
}

function SetupPanel() {
  return (
    <section className="panel border-[var(--risk-medium)] px-5 py-4">
      <h2 className="text-base font-medium">Start the database to continue</h2>
      <p className="caption measure mt-1">
        No <code>DATABASE_URL</code> is configured, so there is nowhere to store a project or its
        chunks. Two commands:
      </p>
      <pre className="tile mt-3 overflow-x-auto border border-[var(--border-subtle)] p-3 text-xs">
        docker compose up -d postgres{"\n"}pnpm db:migrate
      </pre>
      <p className="caption measure mt-3">
        Ollama is also required before an upload can be indexed — it produces the embeddings that
        make the codebase retrievable.
      </p>
    </section>
  );
}

export default async function HomePage() {
  const databaseReady = hasDatabaseConfig();
  const ownerId = await getOwnerId();

  const projectsResult = await loadProjectsForPage(databaseReady ? ownerId : null);
  const projects = projectsResult.ok ? projectsResult.data : [];

  const runs = ownerId ? await loadLatestRunsForPage(ownerId, projects) : new Map();
  const { scorecards, failures } = ownerId
    ? await loadAssessmentsForPage(ownerId, projects)
    : { scorecards: new Map(), failures: new Map<string, string>() };

  // Only projects that actually have a scorecard need their source list: the report
  // is what cites files, and it is only rendered when there is something to explain.
  const scoredProjects = projects.filter((project) => scorecards.has(project.id));
  const sources = ownerId
    ? await loadIndexedSourcesForPage(ownerId, scoredProjects)
    : new Map<string, IndexedSourceListing>();

  return (
    // Wide on purpose: the six-metric scorecard wants one row, the report wants a
    // wide surface with a measured column of prose inside it, and the dependency
    // canvas wants room. Capped so a very wide monitor does not stretch a line of
    // text across the screen — every piece of long-form text carries `.measure`.
    <main className="mx-auto max-w-[1600px] px-5 py-10 sm:px-8 lg:px-12 lg:py-12">
      <header className="flex flex-wrap items-end justify-between gap-x-8 gap-y-3">
        <div>
          <h1 className="text-[1.9rem] font-semibold tracking-tight sm:text-[2.15rem]">
            Migration Compass
          </h1>
          <p className="caption mt-2 max-w-[64ch] text-[0.9375rem] leading-relaxed">
            Assess a legacy codebase&apos;s migration readiness — five computed scores, per-service
            findings, and a dependency graph, on one page that never makes you change tabs.
          </p>
        </div>
      </header>

      <div className="mt-8 flex flex-col gap-8 lg:gap-10">
        {databaseReady ? (
          <>
            <UploadForm />
            {projectsResult.ok ? (
              <ProjectList
                projects={projects}
                runs={runs}
                scorecards={scorecards}
                sources={sources}
                failures={failures}
              />
            ) : (
              // Not the "no projects yet" panel: an unreadable list is a failure, and
              // telling a reader their projects are gone when the database hiccuped is
              // the worst thing this page could say.
              <ErrorNotice
                title="Projects could not be loaded"
                detail={projectsResult.message}
                action="The server log records the reason (search for “Failed to list projects”). Reload the page to try again."
              />
            )}
            <div className="flex flex-col gap-8 lg:gap-10">
              <AskBar projects={projects.map((p) => ({ id: p.id, name: p.name }))} />
              <EnvironmentPanel />
            </div>
          </>
        ) : (
          <SetupPanel />
        )}
      </div>
    </main>
  );
}
