import { AskBar } from "@/components/ask-bar";
import { ProjectList } from "@/components/project-list";
import { UploadForm } from "@/components/upload-form";
import { latestRunsForOwner } from "@/lib/agents/stores";
import type { RunRecord } from "@/lib/agents/run";
import { hasDatabaseConfig } from "@/db/client";
import { embeddingsEnv, isConfigured, llmEnv } from "@/lib/env";
import { getLogger } from "@/lib/observability/logger";
import { listProjectsForOwner, type ProjectSummary } from "@/lib/projects/repository";
import { getOwnerId } from "@/lib/session";

/**
 * The one continuous project page. Layers 1–4 of the design land on this page in
 * later milestones; what exists here is the entry point — upload, session-scoped
 * project list — plus an environment panel so a half-configured deployment
 * explains itself instead of failing opaquely.
 */

function CapabilityRow({ label, detail, ready }: { label: string; detail: string; ready: boolean }) {
  return (
    <li className="flex items-baseline justify-between gap-4 border-b border-[var(--border)] py-2 last:border-b-0">
      <span className="flex items-center gap-2">
        <span
          aria-hidden
          className={`inline-block size-2 rounded-full ${ready ? "bg-[var(--risk-low)]" : "bg-[var(--risk-unknown)]"}`}
        />
        <span className="font-medium">{label}</span>
      </span>
      <span className="text-sm text-[var(--muted)]">{detail}</span>
    </li>
  );
}

function EnvironmentPanel() {
  const embeddingsReady = isConfigured(embeddingsEnv);
  const llmReady = isConfigured(llmEnv);

  return (
    <section className="rounded-lg border border-[var(--border)] bg-[var(--surface)] p-5">
      <h2 className="text-sm font-semibold tracking-wide text-[var(--muted)] uppercase">Environment</h2>
      <ul className="mt-3">
        <CapabilityRow label="Database" detail="configured" ready />
        <CapabilityRow
          label="LLM"
          detail={llmReady ? "configured" : "DEEPSEEK_API_KEY not set — narrative analysis unavailable"}
          ready={llmReady}
        />
        <CapabilityRow
          label="Embeddings"
          detail={embeddingsReady ? `${embeddingsEnv().EMBEDDING_MODEL} via Ollama` : "Ollama not configured"}
          ready={embeddingsReady}
        />
      </ul>
      <p className="mt-4 text-sm text-[var(--muted)]">
        Scores are computed from structured findings by a documented rubric, not generated by a model.
        The scorecard therefore stays available even when the LLM paths are not.
      </p>
    </section>
  );
}

function SetupPanel() {
  return (
    <section className="rounded-lg border border-[var(--risk-medium)] bg-[var(--surface)] p-5">
      <h2 className="text-base font-medium">Start the database to continue</h2>
      <p className="mt-2 text-sm text-[var(--muted)]">
        No <code>DATABASE_URL</code> is configured, so there is nowhere to store a project or its
        chunks. Two commands:
      </p>
      <pre className="mt-3 overflow-x-auto rounded-md border border-[var(--border)] bg-[var(--surface-raised)] p-3 text-xs">
        docker compose up -d postgres{"\n"}pnpm db:migrate
      </pre>
      <p className="mt-3 text-sm text-[var(--muted)]">
        Ollama is also required before an upload can be indexed — it produces the embeddings that
        make the codebase retrievable.
      </p>
    </section>
  );
}

async function loadProjects(ownerId: string | null): Promise<ProjectSummary[]> {
  if (!ownerId) return [];
  try {
    return await listProjectsForOwner(ownerId);
  } catch (error) {
    // The page must still render: a database that is configured but unreachable
    // is a real state, and a crashed page hides the reason.
    getLogger().error({ error }, "Failed to list projects");
    return [];
  }
}

async function loadLatestRuns(
  ownerId: string,
  projects: ProjectSummary[],
): Promise<Map<string, RunRecord>> {
  if (projects.length === 0) return new Map();
  try {
    return await latestRunsForOwner(
      ownerId,
      projects.map((project) => project.id),
    );
  } catch (error) {
    getLogger().error({ error }, "Failed to list analysis runs");
    return new Map();
  }
}

export default async function HomePage() {
  const databaseReady = hasDatabaseConfig();
  const ownerId = await getOwnerId();
  const projects = databaseReady ? await loadProjects(ownerId) : [];
  const runs = ownerId ? await loadLatestRuns(ownerId, projects) : new Map();

  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight">Migration Compass</h1>
        <p className="mt-3 text-[var(--muted)]">
          Assess a legacy codebase&apos;s migration readiness — five computed scores, per-service
          findings, and a dependency graph, on one page that never makes you change tabs.
        </p>
      </header>

      <div className="mt-10 flex flex-col gap-6">
        {databaseReady ? (
          <>
            <UploadForm />
            <ProjectList projects={projects} runs={runs} />
            <AskBar projects={projects.map((p) => ({ id: p.id, name: p.name }))} />
            <EnvironmentPanel />
          </>
        ) : (
          <SetupPanel />
        )}
      </div>
    </main>
  );
}
