import {
  DATA_QUALITY_SATURATION_PER_SERVICE,
  DEFAULT_ASSUMPTIONS,
  EFFORT_WEIGHTS,
  READINESS_WEIGHTS,
  RISK_LEVEL_VALUES,
  TIME_BANDS,
  assumptionsFor,
  clamp,
  round,
  type MigrationAssumptions,
  type RiskLevel,
  type TimeBand,
} from "./assumptions";
import {
  DEFAULT_RISK_WEIGHTING,
  computeRiskScore,
  type RiskWeighting,
  type WeightableService,
} from "./weights";
import {
  computeOperationalAdjustment,
  emptyOperationalAdjustment,
  emptyOperationalSignals,
  type OperationalAdjustment,
  type OperationalSignals,
} from "./operational";

/**
 * The rubric.
 *
 * Pure, synchronous, deterministic. No React, no Next, no database, no model, no
 * network — importing this module cannot reach outside the process, which is what
 * makes "the same input always produces the same scores" a property rather than a
 * promise.
 *
 * The format of every score follows the plan: **scores are computed over the
 * structured findings the pipeline already extracted, never generated by a
 * model.** An LLM-produced number has no traceable "why", which is fatal for
 * something meant to be credible in a migration decision.
 */

export type ScoringFinding = {
  serviceName: string;
  riskLevel: RiskLevel;
  hasTestCoverageGap: boolean;
  dataQualityIssueCount: number;
  requiresMajorRestructuring: boolean;
  /** Distinct dependents, persisted by M3. */
  dependentCount: number;
};

export type ScoringDependency = {
  fromService: string;
  toService: string;
  type: string;
};

/** The Architecture Agent's structured output, as persisted on the run. */
export type ArchitectureInput = {
  currentArchitectureLargelySound: boolean;
  phasedPlan: { phaseNumber: number }[];
};

export type RiskInput = {
  ranked: { serviceName: string; riskLevel: RiskLevel }[];
  operationalDataAvailable: boolean;
};

export type ComparisonInput = {
  matched: string[];
  missed: string[];
  incorrect: string[];
};

export type ScorecardInput = {
  findings: ScoringFinding[];
  dependencies: ScoringDependency[];
  architecture?: ArchitectureInput;
  risk?: RiskInput;
  comparison?: ComparisonInput;
  assumptions?: Partial<MigrationAssumptions>;
  riskWeighting?: RiskWeighting;
  /**
   * Derived operational signals, when the user supplied operational data.
   *
   * Signals rather than raw entries: the reduction from files to measured values
   * happens once, in `operational.ts`, so a score can never depend on which form of
   * the same evidence arrived first. Absent means the code-only baseline.
   */
  operational?: OperationalSignals;
};

export const EVIDENCE_QUALITIES = ["strong", "partial", "limited"] as const;
export type EvidenceQuality = (typeof EVIDENCE_QUALITIES)[number];

export type EvidenceAssessment = {
  level: EvidenceQuality;
  label: string;
  /** Deterministic, human-readable reasons — never model prose. */
  reasons: string[];
};

export type TimeEstimate = {
  weeksMin: number;
  weeksMax: number;
  weeksMid: number;
  /** The plan's band statement, shown verbatim. */
  bandLabel: string;
  band: TimeBand;
  /** The sublinear team-size factor applied to the raw band. */
  teamFactor: number;
};

export type Scorecard = {
  readiness: number;
  risk: number;
  effort: number;
  cost: number;
  personWeeks: number;
  time: TimeEstimate;
  /** The bounded operational adjustment applied to Risk, and its terms. */
  operational: OperationalAdjustment;
  /** Signed Risk points the operational data moved the score, 0 without it. */
  riskDelta: number;
  confidence: {
    /** False once operational data has moved a score. M4 is always code-only. */
    codeOnly: boolean;
    /** `code-only estimate`, or `refined with operational data`. */
    label: string;
    evidence: EvidenceAssessment;
  };
  assumptions: MigrationAssumptions;
  riskWeighting: RiskWeighting;
  counts: { services: number; dependencies: number; phases: number };
};

/**
 * Maps a count onto 0–1 against a reference, saturating at the reference.
 * `count - 1` because one service is the floor of the domain, not zero: a
 * single-service system is the smallest real input, not a degenerate case.
 */
export function normalizeCount(count: number, reference: number): number {
  if (reference <= 1) return count > 0 ? 1 : 0;
  return clamp((count - 1) / (reference - 1), 0, 1);
}

/** Share of the inventory flagged as needing major restructuring. */
export function restructuringShare(findings: ScoringFinding[]): number {
  if (findings.length === 0) return 0;
  return findings.filter((finding) => finding.requiresMajorRestructuring).length / findings.length;
}

/** Share of the inventory with a test-coverage gap. */
export function testCoverageGapShare(findings: ScoringFinding[]): number {
  if (findings.length === 0) return 0;
  return findings.filter((finding) => finding.hasTestCoverageGap).length / findings.length;
}

/** Mean data-quality issues per service, before saturation. */
export function dataQualityPerService(findings: ScoringFinding[]): number {
  if (findings.length === 0) return 0;
  return findings.reduce((sum, finding) => sum + Math.max(0, finding.dataQualityIssueCount), 0) / findings.length;
}

export type EffortBreakdown = {
  raw: number;
  effort: number;
  terms: {
    serviceCount: number;
    phaseCount: number;
    risk: number;
    restructuring: number;
  };
  normalized: {
    serviceCount: number;
    phaseCount: number;
    risk: number;
    restructuring: number;
  };
};

/**
 * Effort (1–10), the plan's documented formula:
 *
 *   normalize(serviceCount)×0.3 + normalize(phaseCount)×0.2 + (risk/100)×0.3 + restructuring×0.2
 *
 * The four weighted terms each land in 0–1, so their sum does too; that sum is
 * then mapped onto the documented 1–10 range as `1 + raw×9`. Mapping rather than
 * scaling by 10 is what keeps a trivial system off the ceiling: one service, one
 * phase, low risk sits near 1, not near 4.
 */
export function computeEffort(input: {
  findings: ScoringFinding[];
  phaseCount: number;
  riskScore: number;
  assumptions?: Partial<MigrationAssumptions>;
}): EffortBreakdown {
  const assumptions = assumptionsFor(input.assumptions);

  const normalized = {
    serviceCount: normalizeCount(input.findings.length, assumptions.referenceServiceCount),
    phaseCount: normalizeCount(input.phaseCount, assumptions.referencePhaseCount),
    risk: clamp(input.riskScore / 100, 0, 1),
    restructuring: restructuringShare(input.findings),
  };

  const terms = {
    serviceCount: normalized.serviceCount * EFFORT_WEIGHTS.serviceCount,
    phaseCount: normalized.phaseCount * EFFORT_WEIGHTS.phaseCount,
    risk: normalized.risk * EFFORT_WEIGHTS.risk,
    restructuring: normalized.restructuring * EFFORT_WEIGHTS.restructuring,
  };

  const raw = terms.serviceCount + terms.phaseCount + terms.risk + terms.restructuring;

  return {
    raw,
    effort: clamp(round(1 + raw * 9, 2), 1, 10),
    terms,
    normalized,
  };
}

/**
 * The band an effort score falls in. Iterates from the top so the shared boundary
 * values (2, 4, 6, 8) belong to the higher band — which is the only assignment
 * that makes the bands tile 1–10 with no gap.
 */
export function bandFor(effort: number): TimeBand {
  const clamped = clamp(effort, 1, 10);
  for (let index = TIME_BANDS.length - 1; index >= 0; index -= 1) {
    const band = TIME_BANDS[index];
    if (band && clamped >= band.minEffort) return band;
  }
  return TIME_BANDS[0] as TimeBand;
}

/**
 * Time, derived FROM Effort and never independently estimated.
 *
 * Two adjustments, both documented:
 *
 * 1. **A monotonic floor.** The plan's bands overlap (effort 3–4 reaches 16 weeks
 *    while effort 5–6 starts at 13), so a naive interpolation would let a harder
 *    project report a shorter timeline. Each band's floor is raised to the
 *    previous band's ceiling, which stays inside the band's documented range and
 *    makes the estimate non-decreasing in effort.
 * 2. **A sublinear team-size factor, ÷√(teamSize ÷ reference).** More engineers
 *    help, but sublinearly — a nod to Brooks's Law rather than pretending
 *    headcount scales linearly. Fewer than the reference team takes *longer*,
 *    which is the honest direction.
 */
export function computeTime(
  effort: number,
  assumptionsInput?: Partial<MigrationAssumptions>,
): TimeEstimate {
  const assumptions = assumptionsFor(assumptionsInput);
  const band = bandFor(effort);
  const index = TIME_BANDS.indexOf(band);

  const previousBand = index > 0 ? TIME_BANDS[index - 1] : undefined;
  const floorWeeks = Math.max(band.minWeeks, previousBand?.maxWeeks ?? 0);

  const span = band.maxEffort - band.minEffort;
  const position = span > 0 ? clamp((clamp(effort, 1, 10) - band.minEffort) / span, 0, 1) : 1;
  const rawWeeks = floorWeeks + position * (band.maxWeeks - floorWeeks);

  const teamFactor = Math.sqrt(assumptions.teamSize / assumptions.defaultTeamSize);

  return {
    weeksMin: round(rawWeeks / teamFactor, 1),
    weeksMax: round(band.maxWeeks / teamFactor, 1),
    weeksMid: round((rawWeeks / teamFactor + band.maxWeeks / teamFactor) / 2, 1),
    bandLabel: band.label,
    band,
    teamFactor: round(teamFactor, 4),
  };
}

export type CostBreakdown = {
  personWeeks: number;
  cost: number;
  durationWeeks: number;
  teamSize: number;
  weeklyRate: number;
};

/**
 * Cost, the plan's documented formula: `effort_in_person_weeks × teamSize ×
 * weeklyRate`.
 *
 * The reading taken here, stated plainly because the formula's shorthand is
 * ambiguous: `duration × teamSize` is the total human effort (person-weeks), and
 * cost is that total multiplied by the blended weekly rate. So team size enters
 * twice — once divided sublinearly into the duration, once multiplying the
 * headcount — and the net effect on cost is √(teamSize), not teamSize.
 */
export function computeCost(input: {
  durationWeeks: number;
  teamSize: number;
  weeklyRate: number;
}): CostBreakdown {
  const personWeeks = input.durationWeeks * input.teamSize;
  return {
    personWeeks: round(personWeeks, 1),
    cost: round(personWeeks * input.weeklyRate, 2),
    durationWeeks: round(input.durationWeeks, 1),
    teamSize: input.teamSize,
    weeklyRate: input.weeklyRate,
  };
}

export type ReadinessBreakdown = {
  readiness: number;
  terms: {
    base: number;
    architectureSound: number;
    lowRiskCredit: number;
    effortPenalty: number;
    restructuringPenalty: number;
    testCoveragePenalty: number;
    dataQualityPenalty: number;
  };
};

/**
 * Migration Readiness (0–100), the plan's inverse-weighted composite: high risk
 * pulls it down, data-quality issues and a missing architecture signal pull it
 * down, and an explicit "the current architecture is largely sound" finding pulls
 * it up.
 *
 * The base is 55, not 100, precisely so the architecture term can *raise* the
 * score — the plan asks for a pulled-up signal, and a ceiling base would make it
 * a no-op. The documented maximum reachable is 100 (sound architecture, lowest
 * risk, no penalties); the minimum on real input is 10.
 */
export function computeReadiness(input: {
  findings: ScoringFinding[];
  architecture?: ArchitectureInput;
  riskScore: number;
  effort: number;
}): ReadinessBreakdown {
  const dataQualitySeverity = clamp(
    dataQualityPerService(input.findings) / DATA_QUALITY_SATURATION_PER_SERVICE,
    0,
    1,
  );

  const terms = {
    base: READINESS_WEIGHTS.base,
    architectureSound:
      input.architecture?.currentArchitectureLargelySound === true
        ? READINESS_WEIGHTS.architectureSound
        : 0,
    lowRiskCredit: (1 - clamp(input.riskScore / 100, 0, 1)) * READINESS_WEIGHTS.lowRiskCredit,
    effortPenalty: (clamp(input.effort, 1, 10) - 1) / 9 * READINESS_WEIGHTS.effortPenalty,
    restructuringPenalty: restructuringShare(input.findings) * READINESS_WEIGHTS.restructuringPenalty,
    testCoveragePenalty: testCoverageGapShare(input.findings) * READINESS_WEIGHTS.testCoveragePenalty,
    dataQualityPenalty: dataQualitySeverity * READINESS_WEIGHTS.dataQualityPenalty,
  };

  const total =
    terms.base +
    terms.architectureSound +
    terms.lowRiskCredit -
    terms.effortPenalty -
    terms.restructuringPenalty -
    terms.testCoveragePenalty -
    terms.dataQualityPenalty;

  return { readiness: clamp(round(total, 2), 0, 100), terms };
}

/**
 * Evidence quality: how much structured input the scores actually rest on.
 *
 * Deterministic and deliberately coarse — three levels, decided by what is
 * present, not by a model's opinion and not by a statistical model. The plan's
 * rule for the whole scoring engine applies here too: a confidence signal that
 * cannot be traced to specific missing inputs is worth nothing.
 */
export function assessEvidence(input: ScorecardInput): EvidenceAssessment {
  const reasons: string[] = [];
  const { findings, dependencies, architecture, risk, comparison } = input;

  if (findings.length === 0) {
    return {
      level: "limited",
      label: "limited evidence",
      reasons: ["No service findings were persisted for this run, so every score rests on an empty inventory."],
    };
  }

  if (findings.length < 2) {
    reasons.push("Only one service was identified, so aggregates are that single service's values.");
  }
  if (dependencies.length === 0) {
    reasons.push(
      "No dependency edges were recorded, so Risk uses equal weighting and the dependency graph is empty.",
    );
  }
  if (!architecture) {
    reasons.push(
      "No architecture output was persisted, so the phased-plan count is 0 and the architecture-soundness " +
        "term contributes nothing.",
    );
  }
  if (!risk) {
    reasons.push("No risk output was persisted, so risk levels come from the Discovery findings alone.");
  } else {
    const ranked = new Set(
      risk.ranked.map((entry) => entry.serviceName.toLowerCase().replace(/[^a-z0-9]+/g, "")),
    );
    const uncovered = findings.filter(
      (finding) => !ranked.has(finding.serviceName.toLowerCase().replace(/[^a-z0-9]+/g, "")),
    );
    if (uncovered.length > 0) {
      reasons.push(
        `${uncovered.length} of ${findings.length} services were not rated by the Risk Agent, so their risk ` +
          `level is Discovery's own estimate.`,
      );
    }
  }
  if (comparison && comparison.missed.length > 0) {
    reasons.push(`The comparison stage flagged ${comparison.missed.length} item(s) the analysis missed.`);
  }

  if (reasons.length === 0) {
    return {
      level: "strong",
      label: "strong structured evidence",
      reasons: [
        `${findings.length} services with structured risk, test-coverage and data-quality fields`,
        `${dependencies.length} typed dependency edges`,
        "an architecture output and a complete risk ranking",
      ],
    };
  }

  return { level: "partial", label: "partial evidence", reasons };
}

/**
 * The scorecard. Deterministic over its input: same input, same five numbers, no
 * I/O and no clock anywhere in the path.
 */
export function computeScorecard(input: ScorecardInput): Scorecard {
  const assumptions = assumptionsFor(input.assumptions);
  const riskWeighting = input.riskWeighting ?? DEFAULT_RISK_WEIGHTING;

  const weightable: WeightableService[] = input.findings.map((finding) => ({
    serviceName: finding.serviceName,
    riskLevel: finding.riskLevel,
    dependentCount: finding.dependentCount,
  }));

  const baseRisk = computeRiskScore(weightable, riskWeighting);

  // Operational data adjusts Risk — and only Risk. Effort, time, cost and readiness
  // then follow from the adjusted figure because they are defined in terms of it, so
  // the adjustment propagates through the rubric's own formulas rather than through
  // a second set of weights that could disagree with them.
  const operational = input.operational
    ? computeOperationalAdjustment(input.operational)
    : emptyOperationalAdjustment(emptyOperationalSignals());

  const risk = clamp(round(baseRisk + operational.delta, 2), 0, 100);
  const phases = input.architecture?.phasedPlan.length ?? 0;

  const effortBreakdown = computeEffort({
    findings: input.findings,
    phaseCount: phases,
    riskScore: risk,
    assumptions: input.assumptions,
  });

  const time = computeTime(effortBreakdown.effort, input.assumptions);
  const cost = computeCost({
    durationWeeks: time.weeksMid,
    teamSize: assumptions.teamSize,
    weeklyRate: assumptions.weeklyRate,
  });

  const readiness = computeReadiness({
    findings: input.findings,
    architecture: input.architecture,
    riskScore: risk,
    effort: effortBreakdown.effort,
  });

  return {
    readiness: readiness.readiness,
    risk,
    effort: effortBreakdown.effort,
    cost: cost.cost,
    personWeeks: cost.personWeeks,
    time,
    operational,
    riskDelta: operational.delta,
    confidence: {
      codeOnly: !operational.applied,
      // The plan's vocabulary, stated rather than left to be inferred from the
      // absence of a badge. It stays `code-only estimate` unless operational data
      // actually moved a number, and even then the refinement is explicitly
      // *measured data*, never model output.
      label: operational.applied ? "refined with operational data" : "code-only estimate",
      evidence: assessEvidence(input),
    },
    assumptions,
    riskWeighting,
    counts: {
      services: input.findings.length,
      dependencies: input.dependencies.length,
      phases,
    },
  };
}

/** Risk-level values, re-exported so a UI can render the mapping without importing two modules. */
export { RISK_LEVEL_VALUES };
export { DEFAULT_ASSUMPTIONS };
