package com.migrationadvisor.chat.service;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.memory.ChatMemory;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;

@Service
public class ChatService {

    private final ChatClient chatClient;

    public ChatService(ChatClient chatClient) {
        this.chatClient = chatClient;
    }

    /**
     * Non-streaming call — waits for the full response before returning.
     * Simple to use for clients that don't need incremental updates (e.g. tests, curl).
     */
    public String chat(String conversationId, String userMessage) {
        return chatClient.prompt()
                .advisors(a -> a.param(ChatMemory.CONVERSATION_ID, conversationId))
                .user(userMessage)
                .call()
                .content();
    }

    /**
     * Streaming call — emits response tokens as they're generated by the model.
     * Backing endpoint exposes this as Server-Sent Events (SSE) so a browser/UI
     * can render the reply incrementally, like a typical chat UI.
     */
    public Flux<String> chatStream(String conversationId, String userMessage) {
        return chatClient.prompt()
                .advisors(a -> a.param(ChatMemory.CONVERSATION_ID, conversationId))
                .user(userMessage)
                .stream()
                .content();
    }
}
